### ISSUE TITLE
Erklärung updaten

### ISSUE THREAD

**Issue by cars10** [softlang/style#1]
Die eingefügte Erklärung am Anfang der Arbeit ist nicht mehr aktuell, siehe
https://www.uni-koblenz-landau.de/de/uni/organisation/verwaltung/abteilungen/abt-3/hsp-ko/dokumente/Grundsaetzliches_Abschlussarbeiten_FB4/view

**Comment by mpaul138** [comment]
Danke für den Hinweis.
Ich habe die Erklärung angepasst.
